version: "3"
services:
    lottery:
        image: lottery-service
        links:
            - database:database
    database:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: postgres
