# Generated by Django 2.1.3 on 2018-11-10 16:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=255)),
            ],
        ),
    ]
